### ISSUE TITLE
Implement the CLI entry point

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#106]
Our program will be started from the command line and should accept a few options:
- `-s` (source): what subset of WET files is this script going to process. Format: range of WET files (indices from `wet.paths`, a file with download paths or smth else).
- `-d` (database): protocol & IP address of the DB. Format: something like `postgresql://localhost:1234`
- `-b` (blob storage): Address or name of the blob storage. Format: something like `wetstorage`. Note: right now stored inside `config.json`
- `-t` (threads): how many worker threads should be spawned
- `-c` (crawl): what crawl should be used. Format: something like `CC-MAIN-2017-13`
- any additional options for special runs (resolve URLs, load terms from file instead of DB, ...)

Explicitly provided parameters override environment variables that override default hardcoded values:
`cli` > `environment` > `default`

**UPDATE**, new definitions as in #130:
- `-w`, `--wet-range` [start]:[end], the subset of WET files to process, e.g. "0:99"
- `-d`, `--db-location` [host]:[port], database location, e.g. "127.0.0.1:5432"
- `-a`, `--db-access` [user]:[password], database access, e.g. "USER:PASSWORD"
- `-b`, `--blob-location` [account]:[container], blob storage location, e.g. "wetstorage:websites"
- `-k`, `--blob-key` [storageKey], blob storage access key, e.g. "AZURE_KEY_HERE"
- `-t`, `--threads` [number], number of worker threads, e.g. "4"
- `-c`, `--crawl` [version], common crawl version, e.g. "CC-MAIN-2017-13"

Default values can be found in `cli.ts` -> `parameters`

**Comment by sacdallago** [comment]
Have not looked at the code yet, but for most params which are default-able, can you fallback?

E.g.: pg --> `postgres://localhost:5432`, **t --> num of cpus (which translates to number of threads, so also virtual cpus)**

**Comment by nyxathid** [comment]
After #130 is reviewed and merged, the last missing thing are environment variables.

**Comment by nyxathid** [comment]
I guess we are done here, #132
