### ISSUE TITLE
Implement complete processing pipeline

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#111]
It's time to connect all our components together! The final pipeline should be similar to this:

From the entry point (`cli.ts`):
- load terms from the DB (use `TermLoader`)
- create a `ProcessingManager` and pass a list of WET file paths to it (stored in a queue)
- load all relevant terms from the DB
- create `n` new `Worker`s, pass the terms to each and start them (asynchronous)
- every `Worker` takes one WET file path, gets the file, filters data and saves relevant pages to Azure+DB (use `Storer`)
- once the `Worker` is done, it fetches the next file path from the `ProcessingManager`

Notes:
- new classes to implement: `Worker` & `ProcessingManager` (naming not final)
- Interactions with DB are not ready yet (#103) -> use dummy function stubs
- the number of `Workers` `n`, a subset of WET files to process and some other parameters should be passed to `cli.ts` (#106)
- If a worker takes too long to process one file (probably an error happened), it should cancel processing, put the WET file path to the end of the queue in `ProcessingManager` and try to process a new file (similar to  #105)

**Comment by lgfrbcsgo** [comment]
Workers need the path to the WET file, Terms and languages to filter for.

**Comment by lgfrbcsgo** [comment]
Ok, I think I understand now. `Worker` is supposed to be a wrapper for `WETManager`, `WebPageDigester` and `LanguageExtractor`? @nyxathid

**Comment by nyxathid** [comment]
That would make sense, it should process one WET file at a time

**Comment by lgfrbcsgo** [comment]
I did some testing now understand what clusters can and can't do.

**Comment by lgfrbcsgo** [comment]
Please help me out with #114.

**Comment by lgfrbcsgo** [comment]
That should be implemented now in 7bcff106b0f4cc3e653c47517d6ed3046252e1e5
