### ISSUE TITLE
Automate downloading and unzipping

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#12]
Create a module for downloading and unzipping .wet files. This should be handled with web workers, so the downloading doesn't have to wait for the unzipping to finish to download the next file. This requires #11 and #10 to be implemented.

**Comment by lgfrbcsgo** [comment]
Also #17

**Comment by lgfrbcsgo** [comment]
Postponed. We should complete the Pre-Processing milestone first and then later start parallelizing the resulting tool chain with web workers.

**Comment by kordianbruck** [comment]
No need to close the issue then @lgfrbcsgo - simply assign it a different milestone and put it in the backlog in your project issue overview

**Comment by lgfrbcsgo** [comment]
It got sort of superseded by issue #32 and doesn't really make any sense any more. That's why I've closed it.
