### ISSUE TITLE
Consistent commandline option naming

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/UnstructuredData#129]
I just went through your cli code and noticed that the naming of your first option is a bit of.
`--wetRange` is using camelCase, while all others are hyphen separated:
`--db-location, --db-access, --blob-location, ...`

**Comment by lgfrbcsgo** [comment]
@nyxathid ...

**Comment by nyxathid** [comment]
Good point, I will change this today :+1:

**Comment by nyxathid** [comment]
BTW we have the same issue in the DB column naming... but way more scary...

**Comment by nyxathid** [comment]
will be fixed in #130

**Comment by nyxathid** [comment]
fixed
