### ISSUE TITLE
Implement stemming and tokenization

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#13]
Create a module which reduces word to their word stems and removes punctuation and common words like "is, a, and, or, etc...".

**Comment by lgfrbcsgo** [comment]
This should replace the `digestFile` function and should take a filepath as a parameter. Since we haven't discussed how to store or further process the results, outputting it to the console should be fine for now.

**Comment by lgfrbcsgo** [comment]
These packages migth be interesting: https://www.npmjs.com/browse/keyword/nlp
In particular https://www.npmjs.com/package/opennlp as it provides tokenization some other cool features. For stemming https://www.npmjs.com/package/node-snowball looks promising.

**Comment by LukasS96** [comment]
I agree on node-snowball, but we need to consider that opennlp requires node-java which seems to me like a little bit to much overhead. What should the result of tokenization look like? I suggest a list of 2-tuples, each with a word and the number of occurences in the document.

**Comment by lgfrbcsgo** [comment]
Valid point, I didn't have a look at opennlp's dependencies. 2-tuples seem like a good start. We also have to remember the amount of websites containing said word.

**Comment by LukasS96** [comment]
Creating the Vector should be done where the parsing module is called since the parsing is done for a single page at a time imo. This would be the same function / module that also takes care of filtering out non-english websites. Can we close this issue?
