### ISSUE TITLE
Storer: connection to DB is not synced (constructor)

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#134]
@Lukas `Storer` has a constructor where it connects to the DB. The constructor returns **before** the connection was established to the DB. Because of that we try to populate the DB before it works and loose some occurrences at the beginning.

We should not connect to DB in the constructor. A special function `connect` taking a callback would be a better option.

**Comment by LukasS96** [comment]
Will do. At some point we should also consider centralizing the database connection somewhere since term-loader also connects to the database and we don't really need two separate connections.

**Comment by LukasS96** [comment]
Actually, I don't see much of a point in implementing this change to storer right now when connecting should take place at some other point. 
For now, I'll refactor our processing manager to create the initial database connection that the other modules can then use.

**Comment by nyxathid** [comment]
fixed in #139 (merged)
similar fix in #137 (still open, not ready at this point of time)
decide which one you like more
