### ISSUE TITLE
Use much more stricter filtering

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#136]
Only save "good" pages to Azure/DB. Right now we save almost everything. 
"good" is defined by many (let's say >10) occurrences of relevant terms.
We too much data and want only the best results.

**Comment by kordianbruck** [comment]
Who can work on this @MusicConnectionMachine/group-2

**Comment by lgfrbcsgo** [comment]
I don't think it's as simple as `at least 10 occurrences`. The heuristic should probably way in the number of different terms and the number of times a single term appears.

**Comment by sacdallago** [comment]
What about a quick and dirty fix? Will it still give an improvement and is it achievable? If so, please proceed :) I mean, if we get 500 nonsense + 100 sense vs 1000 nonsense + 130 sense it's on average much better results, to me.

**Comment by lgfrbcsgo** [comment]
`Math.trunc(#entities / 3 * #terms / 3)` > 1 would be a good heuristic I think. It would require either at least 3 entities or a single entity with 9 different terms for it or anything in between. The weights might need some tuning though.

The best part is that the required score for that heuristic could be passed via CLI or `config.json`, you name it.

**Comment by sacdallago** [comment]
You had me with screenshots of graphs, I'm an easily impressionable person. I like shiny things.

**Comment by lgfrbcsgo** [comment]
> You had me with screenshots of graphs

These are renders by a nice [Wolfram Alpha widget](http://www.wolframalpha.com/widgets/view.jsp?id=f708f36bc40c46f8db505d43ca92053b) @sacdallago

**Comment by lgfrbcsgo** [comment]
I am actually not sure if we even have entities with multiple different terms associated with them... Maybe change `max(#diffrentTermsPerEntity)` to `max(#termsPerEntity)`.

**Comment by goldbergtatyana** [comment]
good job, @lgfrbcsgo ! I also like beautiful visualizations! Now, I just need to understand what it is about :)

#diffrentEntities  - is the number of entities per page? why is it multiplied by 3?
##diffrentTermsPerEntity - what does this number tell us?

Also, why numbers for both variables go up to 4 in your graph?

My suggestion would be to estimate the number of mentions of a term per page -> visualize the distribution -> decide for a cut-off

the visualization would look as folows: a cumulative plot of the number_of_mentions_of_all_terms_we_are_interested_in_per_page (on the x axis) and the percentage_of_pages_having_at_least_the_number_of_mentions_of_all_terms_we_are_interested_in_per_page (on the y axis)

So, 100% of all pages will have at least 0 number of mentions, however only 10% will have 35 mentions and only 5% will have 100 mentions (the numbers are completely fictional, they just illustrate the shape of the curve in the cumulative graph).
Is this description clear?

**Comment by lgfrbcsgo** [comment]
@goldbergtatyana Fully understand that, I think we all had a lecture on that 😎 

`#diffrentEntities` is the number of interesting and unique entities within a page.
`#diffrentTermsPerEntity` is a vector in this case, where each item is the number of unique terms within a page of an entity within that page. So let's say we have 3 interesting entities in a page, then the vector might look like this `[2, 4, 1]`.

The plot is just to visualize what the output of that heuristic will look like. The threshold for the heuristic has to be determined with statistics of course.

Also the `3` is just an arbitrary weight so that the base score of 1 isn't too weak.

**Comment by vviro** [comment]
The discussion will soon become interesting enough to publish a research paper on, but really, people, if the solution is not obviously faulty, it's good enough to go. We need to get the data ASAP, this is the most important thing!

**Comment by lgfrbcsgo** [comment]
> We need to get the data ASAP, this is the most important thing!

> ~~The threshold for the heuristic has to be determined with statistics of course.~~
Testing*

**Comment by vviro** [comment]
Do we have enough time for testing? What's the risk of picking a sub-optimal threshold vs. delaying the data availability by the time necessary for conducting the above testing? Given our current time frame...

**Comment by lgfrbcsgo** [comment]
There should be time to let it run on a single file and have a look at the results? A threshold of 1 should reflect your selection criteria mentioned on Gitter @vviro. We can always make it stricter, that's why I've pushed for a simple function.

**Comment by goldbergtatyana** [comment]
okay any solution is good enough, as major junk will always be removed.

are you saving the numbers in a doc somewhere @lgfrbcsgo ? if yes, pls forward it to me. i could do the cumulative plot as well to speed up the threshold selection criteria.

**Comment by lgfrbcsgo** [comment]
I don't have any numbers right now. I just made that heuristic up. We to run it first after all the fixes to get some output data and then take numbers from that. @goldbergtatyana

**Comment by goldbergtatyana** [comment]
sounds very good to me, thanks for the upfdate @lgfrbcsgo !

**Comment by lgfrbcsgo** [comment]
Ok, the fixes and the heuristic have been implemented. We now have to get everything running... #149

**Comment by sacdallago** [comment]
cool @lgfrbcsgo :) let us know as soon as that happens, we are all very excited @MusicConnectionMachine/jstech

**Comment by lgfrbcsgo** [comment]
You should probably ping @LukasS96 as he's the one with all the experience in Azure :3

**Comment by sacdallago** [comment]
This can be closed, if it's tested. If bugs arise, new issues will follow.

**Comment by lgfrbcsgo** [comment]
> This can be closed, if it's tested. If bugs arise, new issues will follow.

Alrighty, closed.

**Comment by goldbergtatyana** [comment]
@lgfrbcsgo please think about sending me numbers (if you are generating those) for some nice statistics

**Comment by lgfrbcsgo** [comment]
Let's see what I can do. With the Azure Queue is place it's not that trivial to make the test consistent.

**Comment by sacdallago** [comment]
Is this still relevant? IF so, please open a separate issue :) I get cofused when I see closed issues. And db wise: `mcm`

**Comment by felixschorer** [comment]
That shod be covered by #196 @sacdallago
