### ISSUE TITLE
Fix the pre-filters

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#141]
Current filter configuration doesn't work **at all**. Even if we don't split the terms, we get results like "w", "t", "f" in `contains` table. Literally wtf.

Those terms have `entityId` = `null` in `contains`.

**Comment by nyxathid** [comment]
Just run code from #142 and see how many invalid terms we get.

**Comment by lgfrbcsgo** [comment]
Problem has been identified to be the pre-filters.

**Comment by lgfrbcsgo** [comment]
Going to be fixed along with the requested changes in #144
