### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/UnstructuredData#151]
Can you update the readme with some examples on how to use the tool, what is needed, the options that you can specify, etc? :)

E.g. https://github.com/MusicConnectionMachine/RelationshipsG3

**Comment by lgfrbcsgo** [comment]
Check, will do that once we get it running (hopefully later today).

**Comment by kordianbruck** [comment]
@lgfrbcsgo so now is later today - how about it? :stuck_out_tongue:

**Comment by kordianbruck** [comment]
Actually just saw #160 so this can be closed. Awesomo!

**Comment by lgfrbcsgo** [comment]
I suck at closing issues when they should be closed. I either close them too early, too late or let someone else close it because I forgot to @kordianbruck 😿

**Comment by kordianbruck** [comment]
I know, thats why you got me right - Who's your daddy? :man: :dancer:
