### ISSUE TITLE
Check for prefixes and suffixes

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#167]
We definitely have to check that a matched term actually doesn't start within an other word.
The search term `Deo` should find a match in `Video`.

Also checking for suffixes is debatable, I think. Suffixes like a single `s` to indicate the plural or `'s` to indicate the genitive shouldn't prevent a valid match. Though `Deo` might still finde a match in `Deodorant` when not checking for suffixes.

**Comment by lgfrbcsgo** [comment]
Implemented for prefixes in 5b7fe1ae488b37cb4c38f781ddb4b67b53a48443.
This definitely not a perfect solution but a lot better than checking for white spaces, new lines or punctuation in front of a match. That way some prefixes might slip through, but that's better then detecting non-existent prefixes.

**Comment by lgfrbcsgo** [comment]
**IT WERKS!** It reduces the mount of database entries by 6-7 times!

**Comment by goldbergtatyana** [comment]
a nice achievement!

**Comment by lgfrbcsgo** [comment]
Indeed, the most frequent term is now "guitar" instead of "deo".

**Comment by goldbergtatyana** [comment]
this is just funny 😸

**Comment by lgfrbcsgo** [comment]
> this is just funny 😸

Why funny?

**Comment by goldbergtatyana** [comment]
The comment of _deo_ being the most frequent term is funny. I have not realized this was the case before. Very well done fixing this 'funny' issue!

**Comment by lgfrbcsgo** [comment]
Well, `deo` got matched every time there was the word `video` in a webpage.
