### ISSUE TITLE
How are files Stored and Linked to entities  in DB ? 

### ISSUE THREAD

**Issue by ansjin** [MusicConnectionMachine/UnstructuredData#168]
This is just for confirmation if I had missed it. 

While storing the parsed files for an entity in DB do you check the file header that whether it contain the entity name or not and based upon that link with the entity ?
for example 
This is suppose header of your file 
```
WARC/1.0
WARC-Type: conversion
WARC-Target-URI: https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart
WARC-Date: 2017-02-20T08:42:52Z
WARC-Record-ID: <urn:uuid:c81c5c0d-2225-4da0-8277-4a0475019de1>
WARC-Refers-To: <urn:uuid:1b1753cd-884c-4b15-a5c0-199b16b72596>
WARC-Block-Digest: sha1:WB7OAIOPNBB2CSOJJQBVBCNTJJ3NES66
Content-Type: text/plain
Content-Length: 14401
```

Suppose this file also contain some text where the names like Bach or Beethoven are mentioned, so do you link this file to Bach or Beethoven also  ? 
Or do you check the header of the file that it is from wiki - > and Mozart so link only with Mozart as it will mostly be containing information about Mozart .

Can someone add label of discussion and question to this. I think I don't have the permission to do so!

**Comment by ansjin** [comment]
Okay thanks, One more thing How big could be your one file(Approx.) ? 

And Is in DB already some data stored or not yet ?

**Comment by lgfrbcsgo** [comment]
We link a file to every entity occurrence within that file, I think that was your question. It's basically a n to m relation between web pages and entities. A web page can contain multiple entities and an entity can be contained in multiple web pages.

That's basically achieved by the `contains` table:
```
id: 023d9d59-3bda-455b-928b-21c017f1d7c0,
occurrences: {"term":"drum","positions":[1645]},
createdAt: 2017-04-19 20:32:48.934+00,2017-04-19 20:32:48.934+00,
websiteId: 5bd60f95-410e-4a0b-b4eb-cd147b4bdbba,
entityId: 05c5e94f-ae4e-4f9d-8397-8ac97aa57ad1

```

**Comment by ansjin** [comment]
Okay thanks for clarification. If i understood it correctly 
if we have multiple entities in the same website the we will have multiple such entries in contains table with different term and entityID ? 
```

id: 023d9d59-3bda-455b-928b-21c017f1d7c0,
occurrences: {"term":"drum","positions":[1645]},
createdAt: 2017-04-19 20:32:48.934+00,2017-04-19 20:32:48.934+00,
websiteId: 5bd60f95-410e-4a0b-b4eb-cd147b4bdbba,
entityId: 05c5e94f-ae4e-4f9d-8397-8ac97aa57ad1
```

and how is this(**contains table one entry**) linked with the parsed files ?

**Comment by lgfrbcsgo** [comment]
> And Is in DB already some data stored or not yet ?

Yes, there is already data in the database, but there is still some sketchy stuff in there. The tables will be wiped and repopulated later today. 

> if we have multiple entities in the same website the we will have multiple such entries in contains table with different term and entityID ?

Exactly!

> and how is this(contains table one entry) linked with the parsed files ?

The `websiteId` is a foreign key to the `websites` table. This table contains a list of all filtered websites and links to the azure blob storage for each web page.

**Comment by ansjin** [comment]
That's cool, then I can work on that data!

> The websiteId is a foreign key to the websites table. This table contains a list of all filtered websites and links to the azure blob storage for each web page.

So the blob storage will not contain the zipped of multiple websites ? Will it be a single file for each website ? Is the Format of file WET ?

**Comment by lgfrbcsgo** [comment]
I think it's a single zlib deflated file per page? Right, @LukasS96?

**Comment by ansjin** [comment]
It's per page or per website ? I mean whether a website all pages will be in a single WET file or in multiple files ?

**Comment by lgfrbcsgo** [comment]
"Webpage" and "website" both mean a single page in this context. The DB uses "website" while we've switched to "webpage", so that can be a bit confusing I admit. 

So there is only a single WET entry per file.

**Comment by ansjin** [comment]
So if I got it correctly its like for a website, different "**website pages**" are treated as different **websites/web-pages** and each have their **own WET file** and this WET file is specified as an entry in the **websites table** . Right ?

**Comment by lgfrbcsgo** [comment]
- In theory a website consists of **multiple** webpages. 

- We are **only** working with **webpages**.

- Even though the database might call stuff a website, **it still is** a webpage.

**Comment by ansjin** [comment]
Okay thanks for the clarification! I think this issue now can be closed!
