### ISSUE TITLE
Remove transpiled files

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/UnstructuredData#19]
Remove javascript code generated by transpiling the `ts` sources.

Either `.gitignore` all `.js` endings, or build your sources in a specific folder and ignore that!

**Comment by anshul0708** [comment]
Updated in commit [8262c43](https://github.com/MusicConnectionMachine/UnstructuredData/commit/8262c43bb37a3730fede708dc5652a177b432a59)
