### ISSUE TITLE
add a new column to the csv file 

### ISSUE THREAD

**Issue by goldbergtatyana** [MusicConnectionMachine/UnstructuredData#198]
Hi guys, can you please add a new column to he csv file containing the terms that are matched on the websites that you return? I saw that thhough the nice filtering many websites have words 'hotel' or 'travel' in their URL, so having the list of terms that were matched we could filter those additional websites that are not relevant. I could do the manual filtering. Just let me know

**Comment by felixschorer** [comment]
Sure! 

I'd say we'd move the discussion over to #196 though as that issue is meant to be for experimenting with different threshold values and also refining the `term-blacklist.txt` file.
