### ISSUE TITLE
Use path.join() in unpacker.ts

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#23]
Use `path.join(outputFolderPath, outputFileName`) instead of `outputFolderPath + "/" + outputFileName` as it accepts folder paths both, with and without a / at the end.

**Comment by lgfrbcsgo** [comment]
Fixed in ffa08f8

**Comment by sacdallago** [comment]
It's _the only_ accepted way to reference files across the app if you ask me :)

Well done
