### ISSUE TITLE
Search for an alternative to node-snowball?

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#34]
Should we consider switching to a more lightweight solution which doesn't depend on all kinds of stuff?

**Comment by LukasS96** [comment]
We can use this discussion for suggestions, but so far snowball is running fine on my Linux system. If there are better alternatives I don't see why we shouldn't switch.

**Comment by lgfrbcsgo** [comment]
I'll setup a VM for testing then with a watch folder or something

**Comment by lgfrbcsgo** [comment]
An alternative which works well on my machine is https://www.npmjs.com/package/en-stemmer which implements [porter's stemming algorithm](https://www.npmjs.com/package/en-stemmer) in Typescript.

**Comment by lgfrbcsgo** [comment]
Snowball actually uses porter's algorithm internally for stemming english words. http://snowball.tartarus.org/texts/stemmersoverview.html

**Comment by lgfrbcsgo** [comment]
https://www.npmjs.com/package/stemr uses a Typescript implementation of the exact same algorithm snowball uses (porter 2).

**Comment by lgfrbcsgo** [comment]
What do you think @LukasS96 ?

**Comment by lgfrbcsgo** [comment]
https://github.com/iLanguage/iLanguage looks cool as it works with any language. It's based on semin-unsupervised learning though. Not sure how accurate or fast it's going to be.

**Comment by lgfrbcsgo** [comment]
natural node seems to be fix as well. https://github.com/NaturalNode/natural
Remeber that it not does stemming but also tokenizing and tf*idf
