### ISSUE TITLE
Switch from node-snowball to natural

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#35]
https://www.npmjs.com/package/natural
It supports tokenization, stemming and tf-idf, basicially everything we need.
Thoughts?

**Comment by anshul0708** [comment]
This should do the trick, and has a lot more features.

**Comment by nyxathid** [comment]
Does the other/actual package has some advantages? If not, I agree that we can switch to natural. Otherwise we are throwing away some done work

**Comment by LukasS96** [comment]
Natural offers a lot more functionality that we'll need done down the line. Also we won't need two modules for tokenizing and stemming anymore so it probably already simplifies things at this point.

**Comment by lgfrbcsgo** [comment]
@nyxathid that should only be 4 lines in total. If you want I can do it right now?

**Comment by lgfrbcsgo** [comment]
Implemented in 93ecc49

**Comment by sacdallago** [comment]
Seems like a solid NPM package!
