### ISSUE TITLE
Question: Result Data

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/UnstructuredData#40]
Hi, team 3 here :wink: 

which kind of data can we expect from you?
It would be great if you could give us the sentences containing any entities.
It should also be easy for us to find the entities inside the sentences, for example by annotating the text:
```
<artist:Mozart>Mozart</artist> was engaged as a musician at the <place:Salzburg>Salzburg</place> court.
```
or alternatively referencing any occurrences:
```
Mozart was engaged as a musician at the Salzburg court.
artist:Mozart: position 1
place:Salzburg: position 9
```

This is probably also interesting for team @MusicConnectionMachine/group-4 

What do you guys think? Does this make sense to you or do you propose some different approach?

**Comment by nyxathid** [comment]
Hey group 3!
Thanks for the idea of the interface! We will discuss it in the group and reply as soon as possible! Feel free to join us on gitter (https://gitter.im/MusicConnectionMachine/UnstructuredData) and ask/discuss directly there ;)

**Comment by Henni** [comment]
Another thing we just stumbled upon:
Are you planning to connect and annotate pronouns and similar context dependent words to the actual entities?

Example:
> He chose to stay in the capital, where he achieved fame but little financial security. 

This is taken from the Wikipedia article from Mozart. My question is: Will you detect what "he" (Mozart) and "capital" (Salzburg) stand for so that we can work with this. Otherwise we would have to rerun your natural language processing to understand the context.

**Comment by nyxathid** [comment]
@Henni looks like the discussion moved to issue #50

**Comment by sacdallago** [comment]
Then close here?
