### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/UnstructuredData#41]
Are you planning to just search through the "English internet" or are you planning to also search through webpages in other languages?

For classical music it might be interesting to take a look at German, French and Italian pages as well.

**Comment by simonzachau** [comment]
it seems they have thought about [only including English sources](https://github.com/MusicConnectionMachine/UnstructuredData/issues/16)

**Comment by LukasS96** [comment]
We are planning to look at english sources only for now. This is because the package that we're using for stemming only supports english, russian and spanish sources. There is another stemming package with better language support but we decided against using it because it comes with a lot of dependencies.

**Comment by vviro** [comment]
@LukasS96 Could you briefly describe when and why you want to do the stemming?

**Comment by sacdallago** [comment]
In this case I would also opt for english only at the beginning, we can build it up from there!

@vviro @LukasS96 I guess language detection?

**Comment by vviro** [comment]
@sacdallago I think stemming already assumes a certain language, so that's probably not it.

**Comment by LukasS96** [comment]
Actually, I don't think that stemming is necessary for language detection. Using a module like [node-cld](https://github.com/dachev/node-cld) language detection can be done using the actual text content and the top level domain as a hint. This will return the detected language with a confidence value but we have to test how fast it is.

**Comment by LukasS96** [comment]
This way, stemming could be done after filtering out non-english pages. I think it'll be useful because it can reduce computational effort for further processing since there will be a smaller dictionary.

**Comment by vviro** [comment]
I guess the most dangerous/expensive step will be the initial scan/filtering of the whole dataset for relevant entities. After that the size should shrink and more advanced analysis algorithms become computationally viable. So the first question is how this first step should be implemented.

**Comment by vviro** [comment]
... and for this step you guys could use the results of the https://github.com/MusicConnectionMachine/StructuredData/issues/2

**Comment by nyxathid** [comment]
The only supported language so far is English. Other languages could be added later (low priority). Reopen this issue if there are some serious proposals/requests.
