### ISSUE TITLE
Nice representation for the WET entries

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#42]
The WARC package produces objects for each WET entry (webpage text + metadata). We need a nice and typed representation with some additional attributes as filtering priority etc.

Why? Because #42 ;)

**Comment by sacdallago** [comment]
Did you mean? https://www.google.it/webhp?sourceid=chrome-instant&rlz=1C5CHFA_enSG723SG723&ion=1&espv=2&ie=UTF-8#safe=off&q=recursion
