### ISSUE TITLE
Discuss interfaces to Group 1 and 3

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#50]

**Comment by sacdallago** [comment]
? A bit of a more descriptive title or _provide a description_? :)

**Comment by nyxathid** [comment]
@sacdallago a few discussions with group 3 are already running ( #41 , #40 and gitter). We plan to have a group call on 10.03.2017 to clarify more details on interfaces and what data we can expect to get from each other.

**Comment by nyxathid** [comment]
Group 1 - Group 2 interface is discussed here: https://github.com/MusicConnectionMachine/StructuredData/issues/13

**Comment by lgfrbcsgo** [comment]
Proposed interface to Group 3:

```{ "article": "path/to/file", 
"occurrences": [ 
{"term": "Mozart", "type": "composer", "positions": [10, 42] },
{"term": "Salzburg", "type": "city", "positions": [90] }
] }```

**Comment by ansjin** [comment]
This looks great! But one query, the positions mentioned here are with reference to the complete file or a particular sentence ? 

It would be great if they can be with reference to a sentence. 

may be something like this 
```

"positions": 
[
   {"sentenceNumber1": [ 10, 42 ]},
   {"sentenceNumber2": [ 3, 13 ]},
]
```

What do you think...Can it be done ?

**Comment by nyxathid** [comment]
`Sentences`
The data we get from CommonCrawl is basically a raw web page stripped from HTML tags. Sometimes there are single words, sentence fragments or just menu elements. It has no structure at all so it's a bit difficult to define a sentence. To get a feeling, look at this example:
[WET-file-entry.txt](https://github.com/MusicConnectionMachine/UnstructuredData/files/838843/WET-file-entry.txt)
We could include line numbers if it would help you of course.

`Pronouns`
No, we are not matching any pronouns to entities. We have to deal with over 9 TB of data in different languages, so we concentrate on search for promising articles. You can expect a much smaller set of data (in English only) that contains entities defined by group 1. Our natural language processing is limited to basic language detection and stemming. Unfortunately, everything else doesn't scale to our amount of data.

**Comment by Henni** [comment]
@lgfrbcsgo so your positions would currently be just a line number, right?
This brings up another question (similar to Pronouns): Do you handle synonyms? Starting with "Wolfgang Amadeus Mozart" = "Mozart", but also stage names.
If this is the case we would also need the position of the entity within the line.

@nyxathid regarding sentences: this should be good enough. Most of the content we can work with will have some kind of sentence structure. But we will know more when we see example data.
regarding pronouns: so I think we should also ignore the pronouns for now. Let's get going with the easy steps and expand in the future.

**Comment by lgfrbcsgo** [comment]
@Henni I was thinking about position as index within the string.
```
Some random words
New Line Mozart some more words
```
Position of Mozart would be 27 in this example. Basically `"Some random words\nNew Line Mozart some more words".indexOf("Mozart")`

**Comment by kordianbruck** [comment]
@lgfrbcsgo as you moved this back to in progress, can you update us on what you are working on?

**Comment by lgfrbcsgo** [comment]
@kordianbruck I just added it to the project, but everything should have been discussed by now during the presentation week. It therefore can be closed now, I think.
