### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#53]
Summary of the previous discussion started in pull request #47:
@lgfrbcsgo proposed a staggered launch (master thread starting processing chain in worker threads)
@kordianbruck mentoned a worker schema including a queue

**Comment by sacdallago** [comment]
@nyxathid if you use the hash-tag (\#) followed by the number of an issue or a pull request, magic happens! :)

**Comment by nyxathid** [comment]
@sacdallago thx! I was not sure if it's unique because both issues and pull requests use it :D

**Comment by kordianbruck** [comment]
@nyxathid they use the same sequence. If you open an issue it will have 1, the next PR will be 2 - same numbers. It is unique

**Comment by lgfrbcsgo** [comment]
Currently getting worked on in #114
