### ISSUE TITLE
Sample data for groups 3/4

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#58]
We are going to provide some sample data to groups 3/4 as soon as possible. We will provide websites in English that contain at least `n` occurrences of some music related terms. The storage place/server will change in the future but you can expect the data format to be very similar to the final results.

It is still not yet clear how we store website entries: in one BIG file or in many small ones. This probably depends on the file system limitations. I would prefer many small independent files that can be downloaded separately on demand.

**Comment by vviro** [comment]
+1 for smaller or small files

**Comment by nyxathid** [comment]
Here are 100 pages that contain at least 5 composer names:
[CC-MAIN-20170219104612-00150-ip-10-171-10-108.ec2.internal_filtered.warc.zip](https://github.com/MusicConnectionMachine/UnstructuredData/files/850757/CC-MAIN-20170219104612-00150-ip-10-171-10-108.ec2.internal_filtered.warc.zip)

Currently everything is saved in a single file in WARC format. 
Structure:
- Page entries are separated by `\n\n\n`
- Every page has a few-line-long-header and the actual content
- Content is separated from the header with `\n\n`

**Comment by Sandr00** [comment]
FYI: @MusicConnectionMachine/group-3

**Comment by lgfrbcsgo** [comment]
Sample data provided. Can be closed now, I think.
