### ISSUE TITLE
Efficient filtering mechanism

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#59]
Since we have a huge amount of data, we need an efficient filtering mechanism for websites. Basic filtering by terms is already implemented ( #37 ) but can be optimized. Following candidates are possible:
- bloom filter 
- prefix/radix tree

@lgfrbcsgo already had some tests with the bloom filter. 
@nyxathid will implement and test the prefix tree.

**Comment by kordianbruck** [comment]
This is very low priority. Please get the infrastructure set up first

**Comment by lgfrbcsgo** [comment]
Filters are nicely organized now and very easy to use in #95
