### ISSUE TITLE
Module for requesting WET files

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#66]
This module should return a stream of WET file data.
If the file is already present on disk, open the file from disk and return it as a stream.
If not, download file and return a stream of the downloading file. Also pipe stream to store file on disk. 

This way, the caller should not notice a difference in functionality if the file is already downloaded or not. The only difference might be the speed at which the data arrives in the buffer.

With this feature we don't need to take care of whether we already downloaded a WET file or not.

**Comment by nyxathid** [comment]
Very cool! `WAR` is probably `WARC` or `WET`?

**Comment by LukasS96** [comment]
Fixed that one haha

**Comment by nyxathid** [comment]
done in #73 , thx @LukasS96
