### ISSUE TITLE
Automatically retireve cc index info on supplied URLs

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#67]
Implement a function (probably within an extra module) that takes a list of URLs as a Parameter and returns list of common crawl index output for each url.

See: [Common crawl index example](http://index.commoncrawl.org/CC-MAIN-2017-04-index?url=en.wikipedia.org%2Fwiki%2FClassical_music&output=json#)
This is an example request for the url _en.wikipedia.org/wiki/Classical_music_
To get JSON result just perform request in the format http://index_commoncrawl_org/CC-MAIN-2017-04-index?url=<URL>&output=json#

Find a suitable data structure for the cc index response (possibly simply their json format).

**Comment by LukasS96** [comment]
This is required to find all relevant wikipedia pages for groups 3/4 in the crawl data.

**Comment by nyxathid** [comment]
Note: CC index provides links only to WARC files. We have to slightly modify those links to access WET files: replace (`/warc/` -> `/wet/`) and (`warc.gz` -> `warc.wet.gz`) in the file URI.

**Comment by nyxathid** [comment]
implemented in  #75
