### ISSUE TITLE
Data output format (cloud)

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#68]
How do we store output data (website contents) in the cloud storage?

**STRUCTURE**
- option 1: a number of WET files each containing many websites (with headers) 
**Pros**: smaller amount of files; **Cons**: not flexible
- option 2: a single file for each relevant website (**with** headers) 
**Pros**: very flexible, no download overhead; **Cons**: many files
- option 3: a single file for each relevant website (**without** headers) 
**Pros**: least size required, no download overhead; **Cons**: many files

I would prefer option 2. To reduce the number of files per directory, we can organize them as follows:
`root/<WET_file_name>/website_<i>.wet` where `i` is the index of the entry in the WET file

**COMPRESSION**
- option 1: files are stored compressed (e.g. as `.gz`) **Pros**: less size; **Cons**: more complex
- option 2: files are stored uncompressed **Pros**: simpler; **Cons**: faster download/upload

**Comment by LukasS96** [comment]
Well, seems like we did the same thing at the same time :smile:

**Comment by LukasS96** [comment]
I'm going to link this from my issue in G3 and discussion will take place here.

**Comment by Henni** [comment]
### Structure
In my opinion it doesn't hurt to keep some metadata just in case we want to use it sometime in the future, so just keep it in there. Regarding file size I don't have a real opinion, but @vviro voted for small files in a [previous issue](https://github.com/MusicConnectionMachine/UnstructuredData/issues/58#issuecomment-287334600).
So I would go with option 2.

### Compression
I'd go with compression at the beginning and see if this is a bottleneck later.

**Comment by simonzachau** [comment]
I'd also go with this the option to save one file for every relevant website if this is feasible. Otherwise we'd need a function which gets us the relevant website inside a .wet file which is not as intuitive.

**Comment by kordianbruck** [comment]
Option 2 is reasonable only if we have some sort of hierarchy. One could for example take the hash of website name and create a subfolder for the lets say first 3 characters. So you would have:
`x.wet -> 0e96624c92b9823fb1237b57526e4254f82bb64b`
Would be at
```
0/e/9/0e96624c92b9823fb1237b57526e4254f82bb64b
```

According to [this](https://stackoverflow.com/questions/26259727/storing-lots-of-files-in-azure-storage) answer it might be smart to do this, just to increase access speeds. If we never actually list the files, we might just not need any logic / hierarchy to store those files. Also containers might be a strategy as mentioned in the SO answer.

**DID SOMEONE ALREADY LOOK AT AZURE BLOB STORE????**

**Comment by lgfrbcsgo** [comment]
@kordianbruck @LukasS96 has been doing some investigation regarding this.

**Comment by kordianbruck** [comment]
@lgfrbcsgo @LukasS96 please also communicate to Teams 3/4 how to access the blob store

**Comment by RBirkeland** [comment]
@LukasS96 Feel free to contact me about this when you can.

**Comment by nyxathid** [comment]
@LukasS96 are we done with the Azure part of the `Storer` (not asking about the DB interaction, only Azure)?

**Comment by Sandr00** [comment]
@nyxathid, @LukasS96 Is it already decided what we get, regarding the compression?

**Comment by LukasS96** [comment]
Currently we don't compress the data in the blob storage, wouldn't be much trouble to change that, though. @nyxathid mentioned that we should go for compression.

**Comment by Sandr00** [comment]
Please notify me (or anyone in Group Relationships, former 3 or 4) if you change it on the blob, because today I got some links from @nyxathid, so I can get our call-chain running. And I may have to change it, if you compress data.
I can work with both, but I can't switch automatically, because the files currently have no extensions.

**Comment by lgfrbcsgo** [comment]
We've implemented gzip compression now. You've probably already discussed that with @nyxathid today.

**Comment by Sandr00** [comment]
Yes, already implemented in both Groups :+1:

**Comment by nyxathid** [comment]
Compression with `zlib.deflate`/`zlib.inflate` implemented
![giphy](https://cloud.githubusercontent.com/assets/4379052/24801461/97f3d58c-1ba4-11e7-9c2e-7e447ea3cef2.gif)
