### ISSUE TITLE
Use issues

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/UnstructuredData#7]
Please start putting down what you are doing and where you are going in issues. 

We cannot keep track of your work by only looking at your PRs and we have no idea what you want to do.

This group is doing it right: https://github.com/MusicConnectionMachine/VisualizationG5.

You have an entire section on the side ---->
to specify milestones, assign labels, and tell us who is working on what

**Comment by lgfrbcsgo** [comment]
Using issues now.

**Comment by kordianbruck** [comment]
@lgfrbcsgo please also use labels and milestones :+1:
