### ISSUE TITLE
Make sure Travis CI doesn't complain

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#70]
Looks like we started to use Travis CI after the API repo was included as a submodule. 
Right now it is whining with following error messages:
`The command "eval git submodule update --init --recursive " failed 3 times.`
`The command "git submodule update --init --recursive" failed and exited with 1 during .`

**Comment by nyxathid** [comment]
- Fixed API path in #69 , submodule can be cloned now
- `.travis.yml` still missing, disabled "Build only if .travis.yml is present" in Travis CI settings

**Comment by kordianbruck** [comment]
@nyxathid you should really setup the CI server instead of disabling it ;)
