### ISSUE TITLE
Module for creating metadata

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#71]
Implement module which takes a webpage and the list of terms as input and returns metadata if terms were found in said article.

**Comment by nyxathid** [comment]
Some functionality is currently in `term-search.ts`.

**Comment by lgfrbcsgo** [comment]
I know 👍

**Comment by LukasS96** [comment]
This function will not actually store the metadata in the db if i understand correctly? In what form do you plan on returning the output?

**Comment by lgfrbcsgo** [comment]
I'll probably just extend the WebPage class. So as an object.

**Comment by kordianbruck** [comment]
Did you guys already think about creating the models? Or what models you will use?

**Comment by lgfrbcsgo** [comment]
Implemented in #95. Models are currently defined in the API project and in the `WebPage` class in #95.
