### ISSUE TITLE
Module for storing websites: Website data in cloud

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#74]
This should probably all be done by a single module. There should be a call to store a website which will then store the website metadata in the database and the actual website as a blob in azure. This means that we'll have to create a blob storage for this. 

**Cloud Storage**
As discussed in #68 we should probably go with a single file for each website with headers. This file should then be stored as a blob.

**Metadata**
Store the metadata in the database using sequelize (api sub-repo). This means that we first have to complete [api/#26](https://github.com/MusicConnectionMachine/api/issues/26).

This is a big task, so the first step here should be to implement the cloud storage.

**Comment by kordianbruck** [comment]
@LukasS96 I think it would be smarted to split the task up into several sub tasks - no?

**Comment by LukasS96** [comment]
Storing the websites on the blob is already working but that's not much use without the download links in the database which is why I'm working on [api/#26](https://github.com/MusicConnectionMachine/api/issues/26) now
