### ISSUE TITLE
Integrate docker

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/UnstructuredData#80]
so we can deploy this to an awesome appserver on azure

feel free to copy from https://github.com/MusicConnectionMachine/VisualizationG6/blob/develop/Dockerfile

**Comment by lgfrbcsgo** [comment]
Docker support added in #89

**Comment by nyxathid** [comment]
Wait guys, are we already done here?

Not sure how docker and yarn work, but I had to run following on a fresh Ubuntu 16 VM on Azure:
`$ git clone https://github.com/MusicConnectionMachine/UnstructuredData.git`
`$ cd UnstructuredData`
`$ sudo apt-get update`
`$ sudo apt-get install -y nodejs`
`$ sudo apt-get install npm`
`$ sudo npm install node-gyp rebuild`
`$ sudo npm install`
This is just to update node to the latest version, since `apt-get` installs an old v4.xxx
`$ sudo npm cache clean -f`
`$ sudo npm install -g n`
`$ sudo n stable`
`$ sudo ln -sf /usr/local/n/versions/node/7.8.0/bin/node /usr/bin/node `
And finally run our code
`$ tsc`
`$ node out/app.js`

**Comment by sacdallago** [comment]
@nyxathid mh.  


> # Integrate docker
> so we can deploy this to an awesome appserver on azure
> 
> feel free to copy from
> https://github.com/MusicConnectionMachine/VisualizationG6/blob/develop/Dockerfile

Why are you using a VM? What is the ubuntu story?
![](https://media.giphy.com/media/2vlC9FMLSmqGs/giphy.gif)

You don't need a VM on Azure, you quite literally need to deploy an app service, using linux ( Linux app service ) where you pass as container your docker automated build.

**Comment by nyxathid** [comment]
I'm still figuring out how all that stuff works. By "Linux app service", do you mean "Web App On Linux"? There are also other things like "App Service Environment". Or should we use "Azure Container Service" for docker as presented by that Azure guy?

@vviro suggested that we use a queue for tasks. Then we spawn workers that take out tasks from that queue. Does Azure already has predefined configurations for that? I would appreciate any suggestions that would save me a lot of research.

**Comment by kordianbruck** [comment]
@nyxathid go to "Web + Mobile" -> "Web App On Linux" -> under "Configure Container" choose the Tab "Docker Hub" and enter your dockerhub repo name. 

The queue/worker scheme is great. Azure does not have anything ready to go for this as far as I know. Maybe you can do some research on this, but basically you can do it in one container: have multiple threads and every thread is one worker. Only makes sense to have as many threads as CPUs+1/2

**Comment by nyxathid** [comment]
But this is still running on one machine, right?

**Comment by anshul0708** [comment]
@kordianbruck @sacdallago

Do we push our docker images to https://hub.docker.com/u/musicconnectionmachine/ ?

Group 4 are doing this using TravisCI, did you set their envoirment variables for login? Can you do this for us too ?

**Comment by sacdallago** [comment]
@anshul0708 you _can_, but do you have to? Why do you need a docker container for unstructured data? I mean, yes, you could, but the most important thing for you to achieve is to generate a series of scripts that we can call to populate a database.

The section "a bit more about point 4" [here](https://github.com/MusicConnectionMachine/api/issues/1#issue-214357513)

**Comment by nyxathid** [comment]
Closing this issue since upload to docker is actually working. Discussion can be continued in the more general issue #81.
