### ISSUE TITLE
Get this running on azure - #1 priority

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/UnstructuredData#81]
So guys, we really need this to be deployed so teams 3/4 can start running on larger datasets. 

Here are the tasks/roadmap:

1. Please implement the simplest option from https://github.com/MusicConnectionMachine/UnstructuredData/issues/68 
2. Get your CI running https://github.com/MusicConnectionMachine/UnstructuredData/issues/79
3. Setup docker for deployment https://github.com/MusicConnectionMachine/UnstructuredData/issues/80
4. Run your script and start to collect at least **1000** WET files
5. Optimize  so you can grab even more data! (Use threads, more machines, be creative)

@nyxathid please organize the distribution of the tasks to your team members. 

Feel free to use @MusicConnectionMachine/group-3 and @MusicConnectionMachine/group-4 to delegate some work! Bonus points for anyone from the other teams that opens up a pull request on this repo! :100: :1st_place_medal: 

# This is currently the number one priority!

Deadline / Milestone: Wednesday 29.03.2017 @ 18:00
We will have a Hangout session @ 18:15 where we will discuss your progress

**Comment by nyxathid** [comment]
The code can run on Azure but all setup has to be done manually so far. 

Resolved:
- CI works: #79
- Upload to docker works: #80

@sacdallago confirmed following:
- We have to provide a script to populate the DB. The script will be started from the command line.
- We communicate with the DB directly using sequelize, some code will be taken from the API repository (as submodule)

Issues blocking this one:
- No connection to DB: #103, partially #68 (blob storage OK, DB not yet)
- Docker builds were automatized with Travis CI, but the CLI entry point is not implemented yet: #106

**Comment by kordianbruck** [comment]
All of the blockers are implemented.

This issue should also be resolved.
