### ISSUE TITLE
Module for storing websites: Website metadata + downloadlink in db

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#82]
See #74 
This is part 2 of the task and depends on the sequelize definitions for website data in api.

**Comment by nyxathid** [comment]
Uploading to Azure seems to work now. My question: how can I get my file back (download link)?

**Comment by LukasS96** [comment]
Good question, I addressed this in #94.

**Comment by lgfrbcsgo** [comment]
This module should take the `WebPage` objects from #95 objects as an input.

**Comment by lgfrbcsgo** [comment]
Can this be closed? @LukasS96 
This should be merged in cb3ce2e2292e4773c8cf4f4799864e4a82ed7b0d

**Comment by nyxathid** [comment]
Basic functionality works. There are still a few inconsistencies & question. I will close this and create a more specialized issue.
