### ISSUE TITLE
Add option to remove a single cached WET file

### ISSUE THREAD

**Issue by nyxathid** [MusicConnectionMachine/UnstructuredData#88]
Extend WetManager so it can remove cached files by name. 

Why: when download is interrupted, only a part of the WET file is written to disk. When accessing this file later, WetManager will try to load it from disk. This results into an error during unpacking.

This is important for later automation when multiple WET files are processed one by one. In case of an error the partially downloaded file should be deleted.

**Comment by LukasS96** [comment]
Could we maybe add some trigger that unlinks the file automatically when the download stream is interrupted prematurely? This might be a little more elegant if it works, I'll have a look at it later.

**Comment by nyxathid** [comment]
Not sure if it would help if you interrupt the process with Ctrl+C. The most robust way would be either to (1) catch the error that z-lib produces while unpacking or (2) save a list of successfully downloaded files besides the actual WET files. 

Problem with (1) is that the unpacking error is thrown after the stream was already passed to the module that called the WetManager. Problem with (2) is that if a WET file was deleted by someone, the list has to be updated.

**Comment by LukasS96** [comment]
Maybe we should do something like [this](http://stackoverflow.com/questions/14031763/doing-a-cleanup-action-just-before-node-js-exits). 
Also it should be possible to check file size when downloading and delete the file if upon fileoutputstream-closing the filesize on disk is smaller than the filesize in the download header.

**Comment by kordianbruck** [comment]
@lukasstreit is this still needed now that we store multiple websites per WET file?

**Comment by lgfrbcsgo** [comment]
This is no longer needed. It was only need when caching downloaded WET files. We don't use caching. Can be closed.
