### ISSUE TITLE
Accessing the website blobs

### ISSUE THREAD

**Issue by LukasS96** [MusicConnectionMachine/UnstructuredData#94]
As of right now the blob storage access setting is set to private ([Click](https://portal.azure.com/#resource/subscriptions/2fb2b8a4-48ea-4b8c-ae16-0c5e6d19e81d/resourceGroups/group2/providers/Microsoft.Storage/storageAccounts/wetstorage/overview), requires Authorized azure login).
This means that blobs can't be downloaded without an access key. 

Using node js you can download blobs like this:
**1. Create blob service**
`static blobService = azure.createBlobService('wetstorage', <yourstoragekey>);`

**2. Download the blob**
Example from azure:
```
var fs = require('fs');
blobService.getBlobToStream('websites', <blobname>, fs.createWriteStream('output.txt'), 
  function(error, result, response){
    if(!error){
      // blob retrieved
    }
});
```

In the [node js azure blobstorage tutorial](https://docs.microsoft.com/de-de/azure/storage/storage-nodejs-how-to-use-blob-storage) on Azure you can find further information on how to use the blobstorage

### Alternative: public read access
An alternative would be to set the blob access option to 'Blob'. This would mean that a blob can simply be downloaded without an access key using the following url:
https://wetstorage.blob.core.windows.net/websites/{blobname}

Number one would be a little bit more secure but on the other hand the websites stored in the blob storage shouldn't store any sensitive information and could only be read, not modified without an access key. Let me know what you think!

**Comment by kordianbruck** [comment]
@MusicConnectionMachine/group-3 @MusicConnectionMachine/group-4

**Comment by sacdallago** [comment]
Just a note: Remember to make the keys environment variable and cli parameter friendly :)

**Comment by nyxathid** [comment]
+1 to public read access

**Comment by nyxathid** [comment]
First public links already provided to groups 3/4
